/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Hooks: typeof import('src/config/hooks')['default']
  const Http: typeof import('src/service/api')['default']
}
